name: Clang

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Update Submodules
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: git submodule update --init --recursive

    - name: Create Solution Files
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: premake/premake5 gmake2
      
    - name: Build
      run: config=releaseclang_x64 make
    
    - uses: actions/upload-artifact@v2
      with:
        name: build-clang
        path: builds/bin/hsrlekit

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: build-clang
    
    - name: Download Sample File
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: curl https://www.dropbox.com/s/yvsl1lg98c4maq1/video_frame.raw?dl=1 --output video_frame.raw

    - name: Mark as Executable
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: chmod +x hsrlekit

    - name: Dump As Hex, because WTF?
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: xxd video_frame.raw

    - name: Test AVX2
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit video_frame.raw --test --min-time 0 --runs 0 --max-simd avx2
      
    - name: Test AVX
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit video_frame.raw --test --min-time 0 --runs 0 --max-simd avx
      
    - name: Test SSE4.2
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit video_frame.raw --test --min-time 0 --runs 0 --max-simd sse4.2
      
    - name: Test SSE4.1
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit video_frame.raw --test --min-time 0 --runs 0 --max-simd sse4.1
      
    - name: Test SSSE3
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit video_frame.raw --test --min-time 0 --runs 0 --max-simd ssse3
      
    - name: Test SSE3
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit video_frame.raw --test --min-time 0 --runs 0 --max-simd sse3

    - name: Test SSE2
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit video_frame.raw --test --min-time 0 --runs 0 --max-simd sse2
