name: GCC

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Update Submodules
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: git submodule update --init --recursive

    - name: Create Solution Files
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: premake/premake5 gmake2
      
    - name: Build
      run: config=release_x64 make
    
    - uses: actions/upload-artifact@v3
      with:
        name: build-gcc64
        path: builds/bin/hsrlekit

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: build-gcc64
    
    - name: Download Samples
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: git clone https://github.com/rainerzufalldererste/rle_samples.git

    - name: Mark as Executable
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: chmod +x hsrlekit

    - name: Test sample0 AVX2
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit rle_samples/sample0.bin --test --min-time 0 --runs 0 --max-simd avx2
      
    - name: Test sample0 AVX
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit rle_samples/sample0.bin --test --min-time 0 --runs 0 --max-simd avx
      
    - name: Test sample0 SSE4.2
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit rle_samples/sample0.bin --test --min-time 0 --runs 0 --max-simd sse4.2
      
    - name: Test sample0 SSE4.1
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit rle_samples/sample0.bin --test --min-time 0 --runs 0 --max-simd sse4.1
      
    - name: Test sample0 SSSE3
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit rle_samples/sample0.bin --test --min-time 0 --runs 0 --max-simd ssse3
      
    - name: Test sample0 SSE3
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit rle_samples/sample0.bin --test --min-time 0 --runs 0 --max-simd sse3

    - name: Test sample0 SSE2
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit rle_samples/sample0.bin --test --min-time 0 --runs 0 --max-simd sse2

    - name: Test sample0 No-SIMD
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit rle_samples/sample0.bin --test --min-time 0 --runs 0 --max-simd none

    - name: Test sample1 AVX2
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit rle_samples/sample1.bin --test --min-time 0 --runs 0 --max-simd avx2
      
    - name: Test sample1 AVX
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit rle_samples/sample1.bin --test --min-time 0 --runs 0 --max-simd avx
      
    - name: Test sample1 SSE4.2
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit rle_samples/sample1.bin --test --min-time 0 --runs 0 --max-simd sse4.2
      
    - name: Test sample1 SSE4.1
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit rle_samples/sample1.bin --test --min-time 0 --runs 0 --max-simd sse4.1
      
    - name: Test sample1 SSSE3
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit rle_samples/sample1.bin --test --min-time 0 --runs 0 --max-simd ssse3
      
    - name: Test sample1 SSE3
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit rle_samples/sample1.bin --test --min-time 0 --runs 0 --max-simd sse3

    - name: Test sample1 SSE2
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit rle_samples/sample1.bin --test --min-time 0 --runs 0 --max-simd sse2

    - name: Test sample1 No-SIMD
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit rle_samples/sample1.bin --test --min-time 0 --runs 0 --max-simd none

    - name: Test sample2 AVX2
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit rle_samples/sample2.bin --test --min-time 0 --runs 0 --max-simd avx2
      
    - name: Test sample2 AVX
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit rle_samples/sample2.bin --test --min-time 0 --runs 0 --max-simd avx
      
    - name: Test sample2 SSE4.2
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit rle_samples/sample2.bin --test --min-time 0 --runs 0 --max-simd sse4.2
      
    - name: Test sample2 SSE4.1
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit rle_samples/sample2.bin --test --min-time 0 --runs 0 --max-simd sse4.1
      
    - name: Test sample2 SSSE3
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit rle_samples/sample2.bin --test --min-time 0 --runs 0 --max-simd ssse3
      
    - name: Test sample2 SSE3
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit rle_samples/sample2.bin --test --min-time 0 --runs 0 --max-simd sse3

    - name: Test sample2 SSE2
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit rle_samples/sample2.bin --test --min-time 0 --runs 0 --max-simd sse2

    - name: Test sample2 No-SIMD
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit rle_samples/sample2.bin --test --min-time 0 --runs 0 --max-simd none

    - name: Test sample3 AVX2
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit rle_samples/sample3.bin --test --min-time 0 --runs 0 --max-simd avx2
      
    - name: Test sample3 AVX
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit rle_samples/sample3.bin --test --min-time 0 --runs 0 --max-simd avx
      
    - name: Test sample3 SSE4.2
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit rle_samples/sample3.bin --test --min-time 0 --runs 0 --max-simd sse4.2
      
    - name: Test sample3 SSE4.1
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit rle_samples/sample3.bin --test --min-time 0 --runs 0 --max-simd sse4.1
      
    - name: Test sample3 SSSE3
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit rle_samples/sample3.bin --test --min-time 0 --runs 0 --max-simd ssse3
      
    - name: Test sample3 SSE3
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit rle_samples/sample3.bin --test --min-time 0 --runs 0 --max-simd sse3

    - name: Test sample3 SSE2
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit rle_samples/sample3.bin --test --min-time 0 --runs 0 --max-simd sse2

    - name: Test sample3 No-SIMD
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit rle_samples/sample3.bin --test --min-time 0 --runs 0 --max-simd none

    - name: Test sample4 AVX2
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit rle_samples/sample4.bin --test --min-time 0 --runs 0 --max-simd avx2
      
    - name: Test sample4 AVX
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit rle_samples/sample4.bin --test --min-time 0 --runs 0 --max-simd avx
      
    - name: Test sample4 SSE4.2
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit rle_samples/sample4.bin --test --min-time 0 --runs 0 --max-simd sse4.2
      
    - name: Test sample4 SSE4.1
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit rle_samples/sample4.bin --test --min-time 0 --runs 0 --max-simd sse4.1
      
    - name: Test sample4 SSSE3
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit rle_samples/sample4.bin --test --min-time 0 --runs 0 --max-simd ssse3
      
    - name: Test sample4 SSE3
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit rle_samples/sample4.bin --test --min-time 0 --runs 0 --max-simd sse3

    - name: Test sample4 SSE2
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit rle_samples/sample4.bin --test --min-time 0 --runs 0 --max-simd sse2

    - name: Test sample4 No-SIMD
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit rle_samples/sample4.bin --test --min-time 0 --runs 0 --max-simd none

    - name: Test sample5 AVX2
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit rle_samples/sample5.bin --test --min-time 0 --runs 0 --max-simd avx2
      
    - name: Test sample5 AVX
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit rle_samples/sample5.bin --test --min-time 0 --runs 0 --max-simd avx
      
    - name: Test sample5 SSE4.2
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit rle_samples/sample5.bin --test --min-time 0 --runs 0 --max-simd sse4.2
      
    - name: Test sample5 SSE4.1
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit rle_samples/sample5.bin --test --min-time 0 --runs 0 --max-simd sse4.1
      
    - name: Test sample5 SSSE3
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit rle_samples/sample5.bin --test --min-time 0 --runs 0 --max-simd ssse3
      
    - name: Test sample5 SSE3
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit rle_samples/sample5.bin --test --min-time 0 --runs 0 --max-simd sse3

    - name: Test sample5 SSE2
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit rle_samples/sample5.bin --test --min-time 0 --runs 0 --max-simd sse2

    - name: Test sample5 No-SIMD
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit rle_samples/sample5.bin --test --min-time 0 --runs 0 --max-simd none
