name: MSBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  SOLUTION_FILE_PATH: hsrlekit.sln
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Update Submodules
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: git submodule update --init --recursive

    - name: Create Solution Files
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: premake/premake5.exe vs2022

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}} /v:m
    
    - uses: actions/upload-artifact@v2
      with:
        name: build-win64
        path: builds/bin/hsrlekit.exe

  test:
    runs-on: windows-latest
    needs: build

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: build-win64
    
    - name: Download Sample File
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: powershell -Command wget https://www.dropbox.com/s/yvsl1lg98c4maq1/video_frame.raw -OutFile video_frame.raw

    - name: Test AVX2
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit video_frame.raw --test --min-time 0 --runs 0 --max-simd avx2
      
    - name: Test AVX
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit video_frame.raw --test --min-time 0 --runs 0 --max-simd avx
      
    - name: Test SSE4.2
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit video_frame.raw --test --min-time 0 --runs 0 --max-simd sse4.2
      
    - name: Test SSE4.1
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit video_frame.raw --test --min-time 0 --runs 0 --max-simd sse4.1
      
    - name: Test SSSE3
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit video_frame.raw --test --min-time 0 --runs 0 --max-simd ssse3
      
    - name: Test SSE3
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit video_frame.raw --test --min-time 0 --runs 0 --max-simd sse3

    - name: Test SSE2
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./hsrlekit video_frame.raw --test --min-time 0 --runs 0 --max-simd sse2
